---
title: "Materiales y recursos"
---

# Sesiones grabadas

Las sesiones grabadas se encuentran disponibles [**AQUI**](https://uceedu-my.sharepoint.com/:f:/g/personal/anbeltran_uce_edu_ec/EmCl_s2D8EZEpBggXQam-acBoE-tyhH_1gFyrUesTVSWPA?e=ArXwQr){target="_blank"}.

# Datos

Tablas de datos complementarias del curso:

| Nombre      | Descripción                                                                                                                                                  |
|----------------------|--------------------------------------------------|
| rotXLS.xlsx | Datos históricos de casos de rotavirus y variables ambientales de la ciudad de Berlin                                                                        |
| titatic.csv | Datos de sobrevivientes del Titanic en varios niveles de agregación (ejemplo, por género)                                                                    |
| touchon.csv | Datos de depredadores de la rana arbórea de ojos rojos (investigación del [Prof. Justin C. Touchon](https://www.jstor.org/stable/23436298){target="_blank"}) |

Se encuentran disponibles [**AQUI**](https://drive.google.com/file/d/1hy542F5j9OsucWlr8m_R9OaX4lRdDTc1/view){target="_blank"}

# Plantillas de Quarto

| Nombre                                                                                                       | Descripción                                                                                  |
|----------------------|--------------------------------------------------|
| [autoevaluaciones.qmd](https://raw.githubusercontent.com/mmorenozam/progR-website/main/autoevaluaciones.qmd) | Plantilla para responder a las preguntas hechas en las autoevaluaciones a lo largo del curso |
| [ejemplo_reporte.qmd](https://raw.githubusercontent.com/mmorenozam/progR-website/main/ejemplo_reporte.qmd)   | Ejemplo de creación de un reporte en Quarto con un caso de estudio                           |

# Recursos extras

## Libros (gratis)

[Learning Statistics with R](https://learningstatisticswithr.com/){target="_blank"} de Danielle Navarro: excelente libro para comenzar el viaje de aprendizaje de R. Explica conceptos estadísticos de una manera sencilla y evitando complicadas fórmulas tanto como puede.

[Modern Statistics with R](https://modernstatisticswithr.com/){target="_blank"} de Måns Thulin: es un ebook que abarca a mayor profundidad aspectos de operaciones con bases de datos y modelos estadísticos más complejos que los que cubrimos en el curso.

[R for Data Science](https://r4ds.hadley.nz/){target="_blank"} de Hadley Wickham, Mine Çetinkaya-Rundel y Garrett Grolemund: es un excelente recurso para llevar a cabo modelamiento de datos desde los principios más básicos hasta implementación de flujos de trabajo para producción. Está bastante focalizado en el uso del `tidyverse`.

[RStudio para Estadística Descriptiva en Ciencias Sociales](https://bookdown.org/gboccardo/manual-ED-UCH/) de Giorgio Boccardo Bosoni y Felipe Ruiz Bruzzone: es un ebook que contiene buena información en español sobre R. Al menos en para lo que es la manipulación de objetos y estadísticos descriptivos.

## Sitios web

[StackOverflow](https://stackoverflow.com/){target="_blank"}

[towards data science](https://towardsdatascience.com/){target="_blank"}

[STHDA](http://www.sthda.com/english/){target="_blank"}

# Autoevaluaciones corregidas

**Esta sección estará disponible una vez pasada la entrega de la tarea**
