---
title: "Trabajo final"
---

# Generalidades

-   La fecha de entrega del trabajo final al correo mmorenozambrano@protonmail.com será hasta el 25 de Noviembre.

-   Para aprobar el curso es suficiente con presentar las respuestas de las autoevaluaciones. 

-   El análisis de ya sea datos de su autoría o de cualquier otra tabla de datos es **opcional**.

# Formato

-   El formato de entrega será en archivo de extensión .pdf.

-   Durante el transcurso de la última clase (11.11.2023) compartiré un template de Quarto sobre el cual podrán llevar a cabo su trabajo.

# Sugerencias para el análisis de datos

-   Para quiénes opten por crear un reporte que incluya el análisis de datos, les animo a utilizar datos propios.

-   En caso de no contar datos propios, les recomiendo utilizar tablas de datos que hemos visto o mencionado durante el curso. En orden ascendente (de menor a mayor complejidad en su análisis) les enlisto las siguientes:

1.    `iris` y `mtcars` de R de base: son dos tablas que pueden encontrar cientos de ejemplos de su análisis en tutoriales en el internet.

2.    `penguins` del paquete `palmerpenguins`: es ligeramente más compleja por unas cuantas observaciones perdidas y su naturaleza no balanceada. De manera similar, existen cientos de ejemplos en el internet con respecto a su análisis.

3.    Los datos de rotavirus en Berlín (archivo rotXLS.xlsx dados en este curso): corresponden a series de tiempo y los métodos de análisis apropiados para este tipo de datos no es parte del curso. De escoger esta tabla de datos, sean creativos en los análisis que deseen llevar a cabo (no juzgaré si usan o no la metodología correcta).

4.    Los datos de las ranas de Touchon (archivo touchon.csv dados en este curso): estos datos son un poco más complejos por cuanto se deberían considerar muchos supuestos de Estadística para su correcto análisis (que son parte superficial del contenido estadístico del curso). Igualmente que la anterior, les invito a ser creativos en sus análisis si escogen esta tabla.

Finalmente, les dejo otra tabla de datos también interesante, que en nivel de complejidad de su análisis la pondría entre los números 2 y 3 de arriba: 

## Carpitas rinconeras

Del censo de corrientes biológicas de Maryland, se han obtenido datos de la población de carpitas rinconeras (*Rhinichthys cataractae*) en varias corrientes de agua de ese estado. La descripción de esta tabla de datos es la siguiente:

::: columns
::: {.column width="50%"}
-   `Stream`: nombre de la corriente de agua

-   `longnose`: número de carpitas/75 metros de corriente

-   `acerage`: área (acres) drenada por la corriente

-   `DO2`: oxígeno disuelto (mg/L)
:::

::: {.column width="50%"}
-   `maxdepth`: profundidad máxima (cm)

-   `NO3`: concentración de nitrato (mg/L)

-   `SO4`: concentración de sulfato (mg/L)

-   `temp`: temperatura del agua
:::
:::

Los datos se encuentran en el siguiente cuadro de código. Copia, pega y ejecuta el mismo en tu sesión de R para tener la tabla de datos `carpitas` en tu sesión.

```{r echo=T, eval=F, error=T}
Input = ("
Stream                   longnose  acerage  DO2   maxdepth  NO3   SO4     temp
BASIN_RUN                  13         2528    9.6  80        2.28  16.75   15.3
BEAR_BR                    12         3333    8.5  83        5.34   7.74   19.4
BEAR_CR                    54        19611    8.3  96        0.99  10.92   19.5
BEAVER_DAM_CR              19         3570    9.2  56        5.44  16.53   17
BEAVER_RUN                 37         1722    8.1  43        5.66   5.91   19.3
BENNETT_CR                  2          583    9.2  51        2.26   8.81   12.9
BIG_BR                     72         4790    9.4  91        4.1    5.65   16.7
BIG_ELK_CR                164        35971   10.2  81        3.2   17.53   13.8
BIG_PIPE_CR                18        25440    7.5  120       3.53   8.2    13.7
BLUE_LICK_RUN               1         2217    8.5  46        1.2   10.85   14.3
BROAD_RUN                  53         1971   11.9  56        3.25  11.12   22.2
BUFFALO_RUN                16        12620    8.3  37        0.61  18.87   16.8
BUSH_CR                    32        19046    8.3  120       2.93  11.31   18
CABIN_JOHN_CR              21         8612    8.2  103       1.57  16.09   15
CARROLL_BR                 23         3896   10.4  105       2.77  12.79   18.4
COLLIER_RUN                18         6298    8.6  42        0.26  17.63   18.2
CONOWINGO_CR              112        27350    8.5  65        6.95  14.94   24.1
DEAD_RUN                   25         4145    8.7  51        0.34  44.93   23
DEEP_RUN                    5         1175    7.7  57        1.3   21.68   21.8
DEER_CR                    26         8297    9.9  60        5.26  6.36    19.1
DORSEY_RUN                  8         7814    6.8  160       0.44  20.24   22.6
FALLS_RUN                  15         1745    9.4  48        2.19  10.27   14.3
FISHING_CR                 11         5046    7.6  109       0.73   7.1    19
FLINTSTONE_CR              11        18943    9.2  50        0.25  14.21   18.5
GREAT_SENECA_CR            87         8624    8.6  78        3.37   7.51   21.3
GREENE_BR                  33         2225    9.1  41        2.3    9.72   20.5
GUNPOWDER_FALLS            22        12659    9.7  65        3.3    5.98   18
HAINES_BR                  98         1967    8.6  50        7.71  26.44   16.8
HAWLINGS_R                  1         1172    8.3  73        2.62   4.64   20.5
HAY_MEADOW_BR               5          639    9.5  26        3.53   4.46   20.1
HERRINGTON_RUN              1         7056    6.4  60        0.25   9.82   24.5
HOLLANDS_BR                38         1934   10.5  85        2.34  11.44   12
ISRAEL_CR                  30         6260    9.5  133       2.41  13.77   21
LIBERTY_RES                12          424    8.3  62        3.49   5.82   20.2
LITTLE_ANTIETAM_CR         24         3488    9.3  44        2.11  13.37   24
LITTLE_BEAR_CR              6         3330    9.1  67        0.81   8.16   14.9
LITTLE_CONOCOCHEAGUE_CR    15         2227    6.8  54        0.33   7.6    24
LITTLE_DEER_CR             38         8115    9.6  110       3.4    9.22   20.5
LITTLE_FALLS               84         1600   10.2  56        3.54   5.69   19.5
LITTLE_GUNPOWDER_R          3        15305    9.7  85        2.6    6.96   17.5
LITTLE_HUNTING_CR          18         7121    9.5  58        0.51   7.41   16
LITTLE_PAINT_BR            63         5794    9.4  34        1.19  12.27   17.5
MAINSTEM_PATUXENT_R       239         8636    8.4  150       3.31   5.95   18.1
MEADOW_BR                 234         4803    8.5  93        5.01  10.98   24.3
MILL_CR                     6         1097    8.3  53        1.71  15.77   13.1
MORGAN_RUN                 76         9765    9.3  130       4.38   5.74   16.9
MUDDY_BR                   25         4266    8.9  68        2.05  12.77   17
MUDLICK_RUN                 8         1507    7.4  51        0.84  16.3    21
NORTH_BR                   23         3836    8.3  121       1.32   7.36   18.5
NORTH_BR_CASSELMAN_R       16        17419    7.4  48        0.29   2.5    18
NORTHWEST_BR                6         8735    8.2  63        1.56  13.22   20.8
NORTHWEST_BR_ANACOSTIA_R  100        22550    8.4  107       1.41  14.45   23
OWENS_CR                   80         9961    8.6  79        1.02   9.07   21.8
PATAPSCO_R                 28         4706    8.9  61        4.06   9.9    19.7
PINEY_BR                   48         4011    8.3  52        4.7    5.38   18.9
PINEY_CR                   18         6949    9.3  100       4.57  17.84   18.6
PINEY_RUN                  36        11405    9.2  70        2.17  10.17   23.6
PRETTYBOY_BR               19          904    9.8  39        6.81   9.2    19.2
RED_RUN                    32         3332    8.4  73        2.09   5.5    17.7
ROCK_CR                     3          575    6.8  33        2.47   7.61   18
SAVAGE_R                  106        29708    7.7  73        0.63  12.28   21.4
SECOND_MINE_BR             62         2511   10.2  60        4.17  10.75   17.7
SENECA_CR                  23        18422    9.9  45        1.58   8.37   20.1
SOUTH_BR_CASSELMAN_R        2         6311    7.6  46        0.64  21.16   18.5
SOUTH_BR_PATAPSCO          26         1450    7.9  60        2.96   8.84   18.6
SOUTH_FORK_LINGANORE_CR    20         4106   10.0  96        2.62   5.45   15.4
TUSCARORA_CR               38        10274    9.3  90        5.45  24.76   15
WATTS_BR                   19          510    6.7  82        5.25  14.19   26.5
")

carpitas = read.table(textConnection(Input),header=TRUE)
```

## Consideraciones finales

Para quienes opten por presentar el análisis de datos (propios o de otros recursos), **estoy abierto a ofrecer horas de consultoría (sin costo alguno)** para discutir sus resultados de manera personalizada.